BUILD_SHARED_LIBS:BOOL=ON - build out:
Debug:

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Dropbox/eclipse_workspaces/c++/_LIBLO/libloadorder/build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: loadorder32, Configuration: Debug Win32 ------
2>  Building Custom Rule C:/Dropbox/eclipse_workspaces/c++/_LIBLO/libloadorder/CMakeLists.txt
2>  CMake does not need to re-run because C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\build\CMakeFiles\generate.stamp is up-to-date.
2>  error.cpp
2>C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\src\backend\error.cpp(48): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>          C:\_\Microsoft Visual Studio 12.0\VC\include\string.h(112) : see declaration of 'strcpy'
2>  helpers.cpp
2>C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\src\backend\helpers.cpp(39): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>          C:\_\Microsoft Visual Studio 12.0\VC\include\string.h(112) : see declaration of 'strcpy'
2>  game.cpp
2>  plugins.cpp
2>C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\src\backend\plugins.cpp(432): warning C4018: '>' : signed/unsigned mismatch
2>  constants.cpp
2>  libloadorder.cpp
2>  activeplugins.cpp
2>  loadorder.cpp
2>  Generating Code...
2>     Creating library C:/Dropbox/eclipse_workspaces/c++/_LIBLO/libloadorder/build/Debug/loadorder32.lib and object C:/Dropbox/eclipse_workspaces/c++/_LIBLO/libloadorder/build/Debug/loadorder32.exp
2>  loadorder32.vcxproj -> C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\build\Debug\loadorder32.dll
3>------ Build started: Project: tests, Configuration: Debug Win32 ------
3>  Building Custom Rule C:/Dropbox/eclipse_workspaces/c++/_LIBLO/libloadorder/CMakeLists.txt
3>  CMake does not need to re-run because C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\build\CMakeFiles\generate.stamp is up-to-date.
3>  main.cpp
3>C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\src\tests/fixtures.h(116): warning C4244: 'argument' : conversion from 'std::streamoff' to 'unsigned int', possible loss of data
3>gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
3>gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.obj
3>LIBCMT.lib(invarg.obj) : error LNK2005: "void __cdecl _invalid_parameter(unsigned short const *,unsigned short const *,unsigned short const *,unsigned int,unsigned int)" (?_invalid_parameter@@YAXPBG00II@Z) already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: "void __cdecl _invoke_watson(unsigned short const *,unsigned short const *,unsigned short const *,unsigned int,unsigned int)" (?_invoke_watson@@YAXPBG00II@Z) already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __call_reportfault already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __get_invalid_parameter_handler already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __initp_misc_invarg already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __invalid_parameter already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __invoke_watson already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: __set_invalid_parameter_handler already defined in LIBCMTD.lib(invarg.obj)
3>LIBCMT.lib(invarg.obj) : error LNK2005: ___pInvalidArgHandler already defined in LIBCMTD.lib(invarg.obj)
3>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
3>main.obj : error LNK2019: unresolved external symbol "public: __thiscall liblo::Plugin::Plugin(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Plugin@liblo@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "protected: virtual void __thiscall OblivionOperationsTest::AssertInitialState(void)const " (?AssertInitialState@OblivionOperationsTest@@MBEXXZ)
3>main.obj : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall liblo::Plugin::Name(void)const " (?Name@Plugin@liblo@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "protected: virtual void __thiscall OblivionOperationsTest::AssertInitialState(void)const " (?AssertInitialState@OblivionOperationsTest@@MBEXXZ)
3>main.obj : error LNK2019: unresolved external symbol "public: bool __thiscall liblo::Plugin::IsValid(struct _lo_game_handle_int const &)const " (?IsValid@Plugin@liblo@@QBE_NABU_lo_game_handle_int@@@Z) referenced in function "protected: virtual void __thiscall OblivionOperationsTest::AssertInitialState(void)const " (?AssertInitialState@OblivionOperationsTest@@MBEXXZ)
3>C:\Dropbox\eclipse_workspaces\c++\_LIBLO\libloadorder\build\Debug\tests.exe : fatal error LNK1120: 3 unresolved externals
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========